/** Pure renderers for the review artifacts: a waveform preview and a markdown summary. */

export type ReportRow = {
  key: string;
  durationMs: number;
  peak: number;
  rms: number;
  pitchHz: number | null;
  limitMs: number;
  withinLimit: boolean;
};

/** Min/max envelope per column, drawn as one polyline. */
export function renderWaveformSvg(samples: Float32Array, width = 640, height = 120): string {
  const mid = height / 2;
  const points: string[] = [];
  if (samples.length > 0) {
    const perColumn = Math.max(1, Math.floor(samples.length / width));
    for (let x = 0; x < width; x++) {
      const from = x * perColumn;
      if (from >= samples.length) break;
      const to = Math.min(samples.length, from + perColumn);
      let lo = samples[from];
      let hi = samples[from];
      for (let i = from; i < to; i++) {
        if (samples[i] < lo) lo = samples[i];
        if (samples[i] > hi) hi = samples[i];
      }
      points.push(`${x},${(mid - hi * mid).toFixed(2)}`);
      points.push(`${x},${(mid - lo * mid).toFixed(2)}`);
    }
  }
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">`,
    `  <rect width="${width}" height="${height}" fill="#070a14"/>`,
    `  <line x1="0" y1="${mid}" x2="${width}" y2="${mid}" stroke="#1e293b" stroke-width="1"/>`,
    `  <polyline fill="none" stroke="#7fd8ff" stroke-width="1" points="${points.join(' ')}"/>`,
    `</svg>`,
    '',
  ].join('\n');
}

export function renderAudioReport(rows: readonly ReportRow[]): string {
  const over = rows.filter((r) => !r.withinLimit).length;
  const verdict =
    over === 0 ? `all ${rows.length} within the limit` : `${over} of ${rows.length} over the limit`;

  const lines = [
    '# Audio render report',
    '',
    'Generated by `npm run audio:author`. Nothing here ships; these are listening copies.',
    '',
    `Result: ${verdict}.`,
    '',
    '| key | duration | limit | peak | rms | pitch |',
    '|---|---|---|---|---|---|',
  ];
  for (const r of rows) {
    const flag = r.withinLimit ? '' : ' OVER';
    lines.push(
      `| ${r.key} | ${r.durationMs} ms${flag} | ${r.limitMs} ms | ${r.peak.toFixed(3)} | ${r.rms.toFixed(3)} | ${
        r.pitchHz === null ? '—' : `${r.pitchHz.toFixed(2)} Hz`
      } |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}
